"""
PlatformIO pre-build script: generates include/FirmwareRevision.h
containing a FIRMWARE_REVISION string derived from git state.

Registered only for [env:esp32c3] via:
    extra_scripts = pre:scripts/gen_firmware_revision.py

Must stay dependency-free (stdlib only) and must not fail the build
even if git is missing or this isn't a git checkout -- falls back to
the literal "unversioned".
"""
import os
import subprocess

Import("env")

PROJECT_DIR = env.get("PROJECT_DIR") or os.getcwd()
HEADER_PATH = os.path.join(PROJECT_DIR, "include", "FirmwareRevision.h")


def get_git_revision():
    try:
        result = subprocess.run(
            ["git", "describe", "--always", "--dirty"],
            cwd=PROJECT_DIR,
            capture_output=True,
            text=True,
            check=True,
        )
        revision = result.stdout.strip()
        return revision if revision else "unversioned"
    except (FileNotFoundError, subprocess.CalledProcessError, OSError):
        return "unversioned"


def write_header(revision):
    content = (
        "#pragma once\n"
        "// Auto-generated by scripts/gen_firmware_revision.py at build time.\n"
        "// DO NOT EDIT -- DO NOT COMMIT (see .gitignore).\n"
        "\n"
        "static constexpr char FIRMWARE_REVISION[] = \"{}\";\n"
    ).format(revision)

    # Skip the write if content is unchanged, so the header's mtime doesn't
    # churn on every build -- avoids needlessly recompiling everything that
    # includes it when the revision string hasn't actually changed.
    if os.path.exists(HEADER_PATH):
        with open(HEADER_PATH, "r", encoding="utf-8") as f:
            if f.read() == content:
                return

    os.makedirs(os.path.dirname(HEADER_PATH), exist_ok=True)
    with open(HEADER_PATH, "w", encoding="utf-8") as f:
        f.write(content)


write_header(get_git_revision())
