#pragma once
#include <string>
#include <vector>
#include "AppConfig.h"

struct TipCatalog;  // see MeasurementTip::isPlausible() further below

// Result of MeasurementTip::isPlausible() -- whether a new white measurement
// matches the fingerprints collected so far for this tip.
// PlausibleViaFallback = plausible, but
// judged only using a spread estimated from foreign data (too few
// own fingerprints for a direct estimate, see isPlausible()) --
// currently equivalent to Plausible for the UI (only Implausible/
// Indeterminate interrupt the measurement flow, see main.cpp).
enum class PlausibilityResult : uint8_t { Plausible, PlausibleViaFallback, Implausible, Indeterminate };

// Result of MeasurementTip::whiteFingerprintStats() -- per-channel mean
// and ABSOLUTE standard error of the mean (SEM, same unit/
// order of magnitude as 'mean' -- deliberately NOT relative/percentage: the
// normalized values themselves span many orders of magnitude, a
// percentage value alone does not make the absolute order of magnitude visible, see
// main.cpp::renderWhiteFingerprintStats()) over the own fingerprints
// of ONE tip+sensor combination (see isPlausible() for the reasoning
// why only these are comparable to one another). 'mean'/'sem'
// are empty when n == 0; 'sem' is additionally empty when n == 1
// (standard error is not defined there) -- display code (main.cpp) must handle both
// cases.
struct WhiteFingerprintStats {
  size_t n = 0;
  std::vector<float> mean;
  std::vector<float> sem;
};

// A fingerprint: normalized raw measurement (see Spectrometer::normalize())
// + timestamp (main.cpp::uptimeLogger, same convention as
// HistoryStore::MeasurementRecord::uptimeS) + the SensorSettings active
// at measurement time (frozen, NOT the live editable ones -- the same
// asymmetry as AppConfig.h::RootSettings vs. main.cpp::lastMeasurementSettings)
// for later outlier diagnosis (e.g. "was the gain unusually
// low here" instead of prematurely concluding a physical change
// of the tip) + the sensorId (see Spectrometer::sensorId()) of the sensor that
// produced it: 'normalized' is an opaque, sensor-specific Measurement
// (see Spectrometer.h); two fingerprints are only comparable at all if their
// sensorId MATCHES (a plain length comparison would be no
// real guarantee, see MeasurementTip::isPlausible()).
struct WhiteFingerprint {
  uint32_t uptimeS = 0;
  std::string sensorId;
  SensorSettings sensor;
  Measurement normalized;
};

// The oldest entry is dropped as soon as a new one is added and the list
// would already have MAX_WHITE_FINGERPRINTS_PER_TIP entries (see
// main.cpp::appendWhiteFingerprint()).
static const size_t MAX_WHITE_FINGERPRINTS_PER_TIP = 20;

// From how many own fingerprints (with a matching sensorId) onward
// MeasurementTip::isPlausible() estimates mean AND spread directly from them
// (instead of falling back to a foreign sample for the spread). 5 instead of
// fewer, because a sample standard deviation with only 2-3
// degrees of freedom is still very unstable.
static const uint8_t MIN_FINGERPRINTS_FOR_DIRECT_STATS = 5;

// From how many entries (pooled across several comparable groups) onward
// a fallback sample is used at all as the basis for a
// spread estimate -- see isPlausible().
static const uint8_t MIN_FINGERPRINTS_FOR_FALLBACK_STATS = 5;

// A known measurement tip: unique name (currently autogenerated,
// "tip N") + the OpticalSettings that is automatically loaded/applied
// when this tip is activated (see main.cpp::activateTip()) + the
// last white-reference "fingerprints" of this tip (see
// WhiteFingerprint). Further meta-/diagnostic data (not part of
// OpticalSettings) will be added here as additional fields in the future.
struct MeasurementTip {
  std::string name;
  OpticalSettings optical;
  std::vector<WhiteFingerprint> whiteFingerprints;

  // Checks whether 'candidate' (a white measurement just taken, not yet
  // appended, see main.cpp::buildWhiteFingerprint()) matches the previous
  // fingerprints of THIS tip. 'catalog' is only needed for the
  // fallback case (spread estimate from fingerprints of other
  // tips) -- see TipCatalog.cpp for the full derivation.
  PlausibilityResult isPlausible(const WhiteFingerprint& candidate, const TipCatalog& catalog) const;

  // Mean + absolute standard error per channel over the own
  // fingerprints of the given sensorId (typically the sensor that is
  // currently measuring) -- for the "white fingerprint" display screen (main.cpp).
  WhiteFingerprintStats whiteFingerprintStats(const std::string& sensorId) const;
};

// All known measurement tips PLUS which of them is active -- deliberately ONE
// coherent, atomically persisted document (CalibrationStore::
// save/loadTips(), schema/tips.schema.json): "which tip is active" is
// a property OF THE CATALOG (which of the options listed here is currently
// selected), not a RootSettings setting -- RootSettings does not know the
// concept "tip" at all. Invariant (maintained by main.cpp):
// tips is NEVER empty, 'active' ALWAYS refers to an existing entry.
struct TipCatalog {
  std::string active;
  std::vector<MeasurementTip> tips;

  MeasurementTip* find(const std::string& name) {
    for (auto& t : tips) if (t.name == name) return &t;
    return nullptr;
  }
  const MeasurementTip* find(const std::string& name) const {
    for (auto& t : tips) if (t.name == name) return &t;
    return nullptr;
  }
  MeasurementTip* activeTip() { return find(active); }
  const MeasurementTip* activeTip() const { return find(active); }

  // Finds all OTHER tips (name != excludeName) for which 'candidate'
  // would be plausible (Plausible/PlausibleViaFallback), as indices into 'tips'.
  // Sorting: all with a direct Plausible rating first, then all only
  // via PlausibleViaFallback -- each in catalog order. Suggestion
  // list for main.cpp's confirmation screen, when 'candidate' was
  // Implausible/Indeterminate for the ACTIVE tip (see MeasurementTip::
  // isPlausible()).
  std::vector<size_t> rankPlausibleTips(const WhiteFingerprint& candidate, const std::string& excludeName) const;
};
